Unified `created` event
kytos-ng/mef_eline pull request #255
Opened 2023-02-01 17:20 UTC by Alopalao

Closes #253 

Deleted first `created` event from EVC creation since it was being sent twice. Changed `utils.emit_event` argument `name` to `_name` to avoid conflicts with the content of `**kwargs`

Changed `test_handle_link_down()` to work with recent changes.

2023-02-01 17:42 UTC, Ktmi requested changes

2023-02-01 17:50 UTC, Alopalao commented on utils.py
> +def emit_event(controller, _name, context="kytos/mef_eline", **kwargs):
Got it.

2023-02-01 18:05 UTC, Alopalao commented on utils.py
> +def emit_event(controller, _name, context="kytos/mef_eline", **kwargs):
Could it be like this?: `def emit_event(controller, name, context="kytos/mef_eline", extra={}, **kwargs)` 
And the event could be created like:  `KytosEvent(name=event_name, content=kwargs|extra)`
`kwargs` flexibility is already being use by more functions.

2023-02-01 18:22 UTC, Ktmi commented on utils.py
> +def emit_event(controller, _name, context="kytos/mef_eline", **kwargs):
You could do that, but the issue is that it makes reading code like this confusing:
```
emit_event(
    self.controller,
    context="kytos.flow_manager",
    name="flows.install",
    dpid=dpid,
    flow_dict={"flows": switch_flows[dpid][:offset]},
)
```
The point were the content starts, and the other arguments ends isn't clear. By comparison, wrapping the content in a dict is far clearer:

```
emit_event(
    self.controller,
    context="kytos.flow_manager",
    name="flows.install",
    content={
        'dpid`: dpid,
        'flow_dict': {"flows": switch_flows[dpid][:offset]},
    }
)
```

2023-02-01 18:29 UTC, Alopalao commented on utils.py
> +def emit_event(controller, _name, context="kytos/mef_eline", **kwargs):
Ok

2023-02-01 21:22 UTC, Alopalao commented on utils.py
> +def emit_event(controller, _name, context="kytos/mef_eline", **kwargs):
Changed on commit [010e7c06b1ec4f5347f96b4d03dab11f07d6346b](https://github.com/kytos-ng/mef_eline/pull/255/commits/010e7c06b1ec4f5347f96b4d03dab11f07d6346b)

2023-02-01 21:30 UTC, Ktmi approved these changes

2023-02-02 13:47 UTC, italovalcy approved these changes
LGTM! Thanks for the PR, Aldo!

2023-02-02 18:46 UTC, viniarck approved these changes
Nicely done, @Alopalao. :rocket:

2023-02-02 18:47 UTC, merged