Upgrade UI to Vue3
kytos-ng/mef_eline pull request #459
Opened 2024-05-02 19:57 UTC by rmotitsuki

Related to https://github.com/kytos-ng/ui/issues/35

Summary
This PR updates the UI to the Vue3 compatibility framework.
It requires the latest UI to work.

2024-05-19 22:45 UTC, Alopalao requested changes
The buttons `Back to list` and `Redeploy EVC` are misplaced.
![Screenshot_20240519_174626](https://github.com/kytos-ng/mef_eline/assets/55767214/f831d9ef-877e-4e1e-9721-89f454771185)
Traditionally they are at the bottom.

2024-05-28 08:52 UTC, italovalcy requested changes
LGTM. Just left a few comments regarding the maximization of the infoPanels

2024-06-05 17:19 UTC, rmotitsuki commented on ui/k-info-panel/list_connections.kytos
> +}
Changed as requested. I added another calc to fill the screen.

2024-06-05 17:20 UTC, rmotitsuki commented on ui/k-info-panel/show_circuit.kytos
>            title: "View Connections",
Changed as requested.

2024-06-05 18:37 UTC, Alopalao approved these changes
LGTM

2024-06-10 19:26 UTC, merged