Backport node_name fixes to 2023.2.4
kytos-ng/mef_eline pull request #547
Opened 2024-10-24 20:02 UTC by HeriLFIU

Closes #544 

### Summary

Backported node_name fixes to `base/2023.2.4`.

### Local Tests

2024-10-24 20:24 UTC, HeriLFIU commented
@viniarck

2024-10-24 22:04 UTC, Alopalao commented
Nice PR, I tested it and seems to be working as expected. Two things though:
- There is already a version `2023.2.4` with a small change but necessary.
- Lets also apply this [PR](https://github.com/kytos-ng/mef_eline/pull/486) it is for the list of EVCs.

2024-10-24 22:05 UTC, Alopalao requested changes
Nice PR, I tested it and seems to be working as expected. Two things though:
- There is already a version `2023.2.4` with a small change but necessary.
- Lets also apply this [PR](https://github.com/kytos-ng/mef_eline/pull/486) it is for the list of EVCs.

2024-10-25 15:00 UTC, viniarck commented
> Nice PR, I tested it and seems to be working as expected. Two things though:
> 
> * There is already a version `2023.2.4` with a small change but necessary.
> * Lets also apply this [PR](https://github.com/kytos-ng/mef_eline/pull/486) it is for the list of EVCs.

Good observations and great review. 

Regarding `2023.2.4`, can you elaborate on what you mean? It [hasn't been bumped yet](https://github.com/kytos-ng/mef_eline/releases/tag/2023.2.4) or any mentioning regarding any other in-flight conflicting one? 

Also, `kytos.json` needs be bumped, Heriberto.

2024-10-25 17:38 UTC, Alopalao commented
I did not realize it was not released. I made a mistake with the branch [2023.2.4](https://github.com/kytos-ng/mef_eline/tree/base/2023.2.4). The fix is already applied to 2023.2.3.

2024-10-25 17:44 UTC, HeriLFIU commented
@Alopalao oh, so it was already backported?

2024-10-25 18:14 UTC, viniarck reviewed
Looks good to me. I noticed you mentioned the local tests, did you also have the chance to try it out on 2023.2 build too, Heriberto, just to confirm?

I'll let @Alopalao to finish the review, it's great to also have his review. The backport looks good, the other fixes were done in two PRs one fixing `show_circuit.kytos` [on PR 494](https://github.com/kytos-ng/mef_eline/pull/494/) and `list_connections.kytos` [on PR 486](https://github.com/kytos-ng/mef_eline/pull/486), initially on version `2024.1` during its development it was only fixed for one component, but in your backport you addressed both from what I followed based on Aldo's suggestion, let's wait for Aldo confirmation too @HeriLFIU.

2024-10-25 18:36 UTC, Alopalao commented
Sorry for the confusion, the [PR 494](https://github.com/kytos-ng/mef_eline/pull/494) and [PR 486](https://github.com/kytos-ng/mef_eline/pull/486) are not backported to 2023. My confusion was that I saw a branch with 2023.2.4 and I assumed the version was already released, it is not. Proceed this PR with the version 2023.2.4 and please do apply [PR 486](https://github.com/kytos-ng/mef_eline/pull/486) here as well. Both issues have very similar approaches.

2024-10-28 14:34 UTC, HeriLFIU commented
@viniarck I hadn't tried out the new changes on 2023.2, Imma test them now and finish the pr.

2024-10-28 15:20 UTC, HeriLFIU commented
@Alopalao Just tested out all of the UI elements and the changes themselves and everything seems to be in line. I got no errors and the switch names are displayed.
![image](https://github.com/user-attachments/assets/d43d910d-6619-4e14-93f6-7076db4fe781)

2024-10-28 16:14 UTC, Alopalao approved these changes
Great adittion, tested the changes and the dpid names are being waited. I will approve this PR. Do not forget to change the source branch back to 2023.2.3 so it merges with the last release.

2024-10-28 19:26 UTC, viniarck approved these changes
![img](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWdudzRhMXZ6eHV1YTJmd2xzcDNqYnZ6ajFoaGkyZGlzNmhtN2UydyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Hw8vYF4DNRCKY/giphy.gif)

Great PR, and great collaboration, guys. Let's ship it.

2024-10-28 19:29 UTC, merged